# -*- coding: utf-8 -*-
"""Streamlit_bot_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QWsRD4IrLIGFacxEOekYLOWjMan3dfWZ
"""
#pip install openai==0.28
import streamlit as st
import openai
import os

# Set your OpenAI API key here (Or use secrets for secure storage in Streamlit Cloud)

openai_api_key = st.secrets["general"]["OPENAI_API_KEY"]
openai.api_key = openai_api_key

# Initialize chat history (only one system message to define the bot's role)
if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "system", "content": "You are a helpful assistant specialized in the telecom industry."}
    ]

# Chatbot Function
def chatbot():
    # Get the user input
    user_input = st.text_input("You: ", key="user_input")
    
    if user_input:
        # Add the user input to the message history
        st.session_state.messages.append({"role": "user", "content": user_input})
        
        # Request the response from OpenAI's API
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=st.session_state.messages,
            temperature=0.2
        )
        
        # Get the bot's reply
        reply = response["choices"][0]["message"]["content"]
        
        # Display the bot's reply
        st.write(f"**Bot:** {reply}")
        
        # Append the bot's response to the message history
        st.session_state.messages.append({"role": "assistant", "content": reply})

# Main Code to Run the Chatbot
st.title("Telecom Industry Chatbot")
st.write("You can now chat with the bot! Type 'exit' or 'quit' to stop the chat.")

# Call the chatbot function
chatbot()